// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lS7OBw23C9ND7G4GrkpLjSgsQpqDqeo',
    appId: '1:659809467218:web:53c4c22026c1bdf631d88b',
    messagingSenderId: '659809467218',
    projectId: 'ipmedt4-groep10',
    authDomain: 'ipmedt4-groep10.firebaseapp.com',
    storageBucket: 'ipmedt4-groep10.appspot.com',
    measurementId: 'G-GE0X72QR8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9OvW7p2t4z_qK8Y0uBaeU8gEvUgigpo',
    appId: '1:659809467218:android:78024120bb29534631d88b',
    messagingSenderId: '659809467218',
    projectId: 'ipmedt4-groep10',
    storageBucket: 'ipmedt4-groep10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKqIQgyyNCcwa-nzDYpo-356NtQXkTBzM',
    appId: '1:659809467218:ios:073ca75eb3db7ab531d88b',
    messagingSenderId: '659809467218',
    projectId: 'ipmedt4-groep10',
    storageBucket: 'ipmedt4-groep10.appspot.com',
    iosBundleId: 'com.example.ipmedt4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKqIQgyyNCcwa-nzDYpo-356NtQXkTBzM',
    appId: '1:659809467218:ios:073ca75eb3db7ab531d88b',
    messagingSenderId: '659809467218',
    projectId: 'ipmedt4-groep10',
    storageBucket: 'ipmedt4-groep10.appspot.com',
    iosBundleId: 'com.example.ipmedt4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6lS7OBw23C9ND7G4GrkpLjSgsQpqDqeo',
    appId: '1:659809467218:web:98edf0c21fc895f031d88b',
    messagingSenderId: '659809467218',
    projectId: 'ipmedt4-groep10',
    authDomain: 'ipmedt4-groep10.firebaseapp.com',
    storageBucket: 'ipmedt4-groep10.appspot.com',
    measurementId: 'G-5YYXJKB2JP',
  );
}
